export const UNITY_APP_WEBSOCKET_HOST = "127.0.0.1";
export const UNITY_APP_WEBSOCKET_PORT = 8080;

export const VOICE_COMMAND_APP_WEBSOCKET_HOST = "127.0.0.1";
export const VOICE_COMMAND_APP_WEBSOCKET_PORT = 5174;
