on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn build
